#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Venancio García

# Short bio or description (displayed in the header)
description: Estudiante de Ingeniería Industrial

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://lh3.googleusercontent.com/AOkrKkD_DRW1paK302Drnq9qrLoG5CzxMfbsB4zlyHYomM9WNDQWkhfoSmNXBJPg79GZgTzv7DFRwDxXAag-1ht-GnOtA6f7HVVc611sgq7OreSAI90vHrYZNKZE2d_Tk1eTQxoO3F2I3iGARqA1P8gSobWbq-N-CgGUmeoX8LtRh9bRnNRlRUAqiic-kAtBujAhHwN4Ayj29QX6rp2HGUfzfS_8RGak0DOn2PTe5y608duBe2zsJ2_hDqLbwbMolZp8Th8-tBTWcYj6NIZTsm1qUAFh4KRmngg3wI4SFTczYLpo5K9_4ecbXZIac2syn9NvKrWTd0sUJR6W0WEpFHrRfDTTci3rcoznyICVhMZOfDvSD-FxAARGGZ_syh8-cuPSJmdeykeswqfJNb9wa-NvDrwqMCI_fL3UD2iPqDUwIrZc-BC9j4Rzqc7ENEJ-3vxnELBgObIZF4Ao3h4sNNepG7QwDCnD2PeLioOxos6hL-EG1pw-0DLz25Z0h1Yz1nyZp1BBpFWCEpSXzakg4NbQ5vQ5I2LXVEW_bt1NkVWUSKJ867ZAzC1Fg7ablRfv2YCeStU24lJaWdnUSFYw5qH0fV8P31InzpGjRC5CaxtM3crc1QQpjaRRSJacg58iFTS4ilXpPll_2RDlCP8-zkvrKK5GrT1vCCNg_H5PkydRhp4UCG5BKiMYvUiz577cUObluJEBctEGC7IbeK7YEeBT8w=w771-h866-no?authuser=0

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: venanciogarmun@gmail.com
  facebook:
  flickr:
  github: Venanciogar10
  instagram:
  linkedin: Venancio García Muñoz
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
